language: android

# Turning off caching to avoid caching Issues
# cache: false
# Using the new Container-Based Infrastructure
sudo: false

env:
  global:
    # Amount of memory granted to Gradle JVM
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  
before_install:
    # Making sure gradlew has executable permissions
    - chmod +x gradlew
    # for gradle output style
    - export TERM=dumb
    
android:
  components:
    # The BuildTools version we are using for our project
    - build-tools-23.0.2
    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
     - 'android-sdk-license-.+'

script:
  ./gradlew :animators:clean :animators:build
